// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://izgwlyugpavuggqqzqkv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml6Z3dseXVncGF2dWdncXF6cWt2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MzMxODQsImV4cCI6MjA3MDQwOTE4NH0.WyWKxCDaaLfM1Tw5ZH6RqyrooMNSnYANCxTI5HrMQys";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});