name: Build and Commit Email HTML
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - name: Commit build output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          mkdir -p email-build
          cp -r dist/* email-build/
          git add email-build
          git commit -m "Update compiled email HTML" || echo "No changes to commit"
          git push
