name: Publish static email to Pages
on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build email-build from the /email folder
      - name: Build email-build
        shell: bash
        run: |
          set -e
          rm -rf email-build
          mkdir -p email-build
          # copy HTML + assets folder from /email
          cp -r email/* email-build/

      # Rewrite /paths in HTML to absolute GitHub Pages URLs
      - name: Rewrite asset paths
        shell: bash
        run: |
          set -e
          BASE="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          if ls email-build/*.html >/dev/null 2>&1; then
            find email-build -type f -name "*.html" -print0 | xargs -0 sed -i \
              -e "s|src=\"/|src=\"${BASE}/|g" \
              -e "s|href=\"/|href=\"${BASE}/|g" \
              -e "s|url(/|url(${BASE}/|g"
          else
            echo "No HTML files in email-build"; exit 1
          fi

      - name: Commit compiled email
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add email-build || true
          git commit -m "Update static email" || echo "No changes"
          git push || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: email-build

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
