name: Drop-to-Brevo: make email-build from Lovable export
on:
  push:
    branches: [ main ]
    paths:
      - 'drop/**'
      - 'email/**'
      - '.github/workflows/build-and-pages.yml'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build email-build (pick source + sweep assets)
        shell: bash
        run: |
          set -e
          rm -rf email-build
          mkdir -p email-build/assets

          # choose source HTML (prefer drop/index.html)
          if [ -f drop/index.html ]; then
            SRC=drop/index.html
          elif [ -f email/index.html ]; then
            SRC=email/index.html
          elif [ -f email/email.html ]; then
            SRC=email/email.html
          else
            echo "No source HTML found. Add drop/index.html or email/index.html"; exit 1
          fi
          cp "$SRC" email-build/email.html

          # sweep assets (ignore missing dirs)
          rsync -a drop/assets/  email-build/assets/  2>/dev/null || true
          rsync -a email/assets/ email-build/assets/ 2>/dev/null || true
          rsync -a public/       email-build/assets/ 2>/dev/null || true
          rsync -a src/assets/   email-build/assets/ 2>/dev/null || true

      - name: Rewrite paths and clean HTML
        shell: bash
        run: |
          set -e
          BASE="https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}"
          HTML=email-build/email.html

          # remove Cloudflare email decode script
          sed -i '/cloudflare-static\/email-decode.min.js/d' "$HTML"

          # replace Cloudflare obfuscated anchor with plain mailto
          sed -i 's|<a href="/cdn-cgi[^"]*"[^>]*>[^<]*</a>|<a href="mailto:ksampson@capitalsolutionsbancorp.com">ksampson@capitalsolutionsbancorp.com</a>|g' "$HTML"

          # normalize paths to absolute Pages URLs
          sed -i \
            -e "s|https://your-domain.com/|${BASE}/|g" \
            -e "s|src=\"/|src=\"${BASE}/|g" \
            -e "s|href=\"/|href=\"${BASE}/|g" \
            -e "s|url(/|url(${BASE}/|g" \
            -e "s|src=\"\./assets/|src=\"${BASE}/assets/|g" \
            -e "s|href=\"\./assets/|href=\"${BASE}/assets/|g" \
            -e "s|url(\./assets/|url(${BASE}/assets/|g" \
            -e "s|src=\"assets/|src=\"${BASE}/assets/|g" \
            -e "s|href=\"assets/|href=\"${BASE}/assets/|g" \
            -e "s|url(assets/|url(${BASE}/assets/|g" \
            "$HTML"

      - name: Commit compiled email
        shell: bash
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add email-build || true
          git commit -m "Update Brevo-ready email" || echo "No changes"
          git push || true

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: email-build

  deploy:
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
